### ISSUE TITLE
Relative paths not supported

### ISSUE THREAD

**Issue by hyandell** [awslabs/yesiscan#6]
If I run 'yesiscan [dir]' I get errors, currently it has to be 'yesiscan /full/path/to/dir'. Would love to be able to do it locally.

**Comment by ovalba** [comment]
I think we need to double check if this is still happening, and if do, we need to fix this for Lite MVP

**Comment by amznpurple** [comment]
This is fixed.

**Comment by ovalba** [comment]
Tested with latest version and it's fixed. Please reopen if still happening
